# Generated by Django 2.2.19 on 2021-11-30 08:55

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# fail.migrations.0003_auto_20211130_0952
def create_some_data(apps, schema_editor):
    modela = apps.get_model('fail', 'ModelA')
    a = modela(some_field=1)
    a.save()
    b = modela(some_field=2)
    b.save()

    modelb = apps.get_model('fail', 'ModelB')
    modelb.objects.filter(some_other_field=1).update(model_a=a)
    modelb.objects.filter(some_other_field=2).update(model_a=b)


class Migration(migrations.Migration):

    replaces = [('fail', '0001_initial'), ('fail', '0002_modelb_model_a'), ('fail', '0003_auto_20211130_0952'), ('fail', '0004_auto_20211130_0955')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_other_field', models.IntegerField()),
                ('model_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fail.ModelA')),
            ],
        ),
        migrations.RunPython(create_some_data),
        migrations.AlterField(
            model_name='modelb',
            name='model_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fail.ModelA'),
        ),
    ]
