# Generated by Django 2.2.19 on 2021-11-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelb',
            name='model_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fail.ModelA'),
        ),
    ]
