# Generated by Django 2.2.19 on 2021-11-30 08:52

from django.db import migrations


def create_some_data(apps, schema_editor):
    modela = apps.get_model('fail', 'ModelA')
    a = modela(some_field=1)
    a.save()
    b = modela(some_field=2)
    b.save()

    modelb = apps.get_model('fail', 'ModelB')
    modelb.objects.filter(some_other_field=1).update(model_a=a)
    modelb.objects.filter(some_other_field=2).update(model_a=b)


class Migration(migrations.Migration):

    dependencies = [
        ('fail', '0002_modelb_model_a'),
    ]

    operations = [
        migrations.RunPython(create_some_data),
    ]
