# Generated by Django 2.2.19 on 2021-11-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fail', '0003_auto_20211130_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelb',
            name='model_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fail.ModelA'),
        ),
    ]
